"""Shared constants for the fire mission."""

NO_COMMAND = 12.0
FOLLOW_HUMAN_COMMAND = 8.0
NO_PLAN = 99.0
NO_RECENT_TASK = -1.0
NO_ID_REQUEST = 0.0

TASK_DONE_CODES = {3.0, 4.0}
PLAN_ACCEPT_PRIMARY = 1.0
PLAN_ACCEPT_SECONDARY = 2.0

DREF_RESET_WINGMAN = "custom/haato/reset_wingman"
DREF_PAUSED = "sim/time/paused"
DREF_PARTICIPANT_ID = "custom/haato/participant_id"
DREF_INITIATIVE_LEVEL = "custom/haato/initiative_level"
DREF_RESET_MISSION = "custom/haato/reset_mission"
DREF_START_LOGGING = "custom/haato/start_logging"
DREF_FIRE_LAYOUT = "custom/haato/fire_layout"
DREF_LOG_FILE_IDENTIFIER = "custom/haato/log_file_identifier"
DREF_WIND_DIRECTION = "custom/haato/wind_direction"
DREF_CONTROL_PREFIX = "custom/haato/control_prefix"
DREF_SHOW_PRIMARY_SCREEN = "custom/haato/show_primary_screen"
DREF_CURRENT_SCREEN = "custom/haato/current_screen"
DREF_CHANGE_SCREEN = "custom/haato/change_screen"
DREF_MAP_ZOOM_RANGE = "custom/haato/map_zoom_range"
DREF_HUMAN_IN_RANGE = "custom/haato/human_in_range_of_target"
DREF_HUMAN_REQUESTS_PLAN = "custom/haato/human_requests_plan_suggestion"
DREF_COMMAND_FROM_HUMAN = "custom/haato/command_from_human"
DREF_HELP_REQUEST = "custom/haato/help_request"
DREF_HELP_REQUEST_RESPONSE = "custom/haato/help_request_response"
DREF_TARGET_STATUS_FMT = "custom/haato/target_status[{target_id}]"
DREF_TARGET_CLASSIFICATION_FMT = "custom/haato/target_classification[{target_id}]"
DREF_TARGET_WHOFLEW_INITIAL_FMT = "custom/haato/target_whoflew_initial[{target_id}]"

CONTROL_PREFIX_MAP = {
    "thrustmaster": 1.0,
    "microsoft": 4.0,
    "logitech": 0.0,
}

PLUGIN_DEFAULT_PARTICIPANT_ID = 99.0
PLUGIN_DEFAULT_LOG_FILE_IDENTIFIER = 0.0
PLUGIN_DEFAULT_FIRE_LAYOUT = 99.0
PLUGIN_DEFAULT_INITIATIVE_LEVEL = 99.0
PLUGIN_DEFAULT_WIND_DIRECTION = 150.0
PLUGIN_DEFAULT_CONTROL_PREFIX = 99.0
PLUGIN_DEFAULT_SHOW_PRIMARY_SCREEN = 0.0
PLUGIN_DEFAULT_CURRENT_SCREEN = -1.0
PLUGIN_DEFAULT_CHANGE_SCREEN = -1.0
PLUGIN_DEFAULT_RESET_MISSION = 0.0
PLUGIN_DEFAULT_START_LOGGING = 0.0
PLUGIN_DEFAULT_MAP_ZOOM_RANGE = -1.0
PLUGIN_DEFAULT_RESET_WINGMAN = 0.0
PLUGIN_DEFAULT_COMMAND_FROM_HUMAN = 99.0
PLUGIN_DEFAULT_HUMAN_REQUESTS_PLAN = 0.0
PLUGIN_DEFAULT_HUMAN_IN_RANGE = 99.0
PLUGIN_DEFAULT_TARGET_STATUS = 0.0
PLUGIN_DEFAULT_TARGET_CLASSIFICATION = 0.0
PLUGIN_DEFAULT_TARGET_WHOFLEW_INITIAL = -1.0

PLUGIN_RESET_DREF_DEFAULTS = (
    (DREF_PARTICIPANT_ID, PLUGIN_DEFAULT_PARTICIPANT_ID),
    (DREF_LOG_FILE_IDENTIFIER, PLUGIN_DEFAULT_LOG_FILE_IDENTIFIER),
    (DREF_FIRE_LAYOUT, PLUGIN_DEFAULT_FIRE_LAYOUT),
    (DREF_INITIATIVE_LEVEL, PLUGIN_DEFAULT_INITIATIVE_LEVEL),
    (DREF_WIND_DIRECTION, PLUGIN_DEFAULT_WIND_DIRECTION),
    (DREF_CONTROL_PREFIX, PLUGIN_DEFAULT_CONTROL_PREFIX),
    (DREF_SHOW_PRIMARY_SCREEN, PLUGIN_DEFAULT_SHOW_PRIMARY_SCREEN),
    (DREF_CHANGE_SCREEN, PLUGIN_DEFAULT_CHANGE_SCREEN),
    (DREF_CURRENT_SCREEN, PLUGIN_DEFAULT_CURRENT_SCREEN),
    (DREF_RESET_MISSION, PLUGIN_DEFAULT_RESET_MISSION),
    (DREF_START_LOGGING, PLUGIN_DEFAULT_START_LOGGING),
    (DREF_MAP_ZOOM_RANGE, PLUGIN_DEFAULT_MAP_ZOOM_RANGE),
    (DREF_RESET_WINGMAN, PLUGIN_DEFAULT_RESET_WINGMAN),
    (DREF_COMMAND_FROM_HUMAN, PLUGIN_DEFAULT_COMMAND_FROM_HUMAN),
    (DREF_HUMAN_REQUESTS_PLAN, PLUGIN_DEFAULT_HUMAN_REQUESTS_PLAN),
    (DREF_HUMAN_IN_RANGE, PLUGIN_DEFAULT_HUMAN_IN_RANGE),
)
